export const TYPE_SYMBOL_LETTERS = {
  Normal: 'C',
  Fire: 'r',
  Water: 'W',
  Grass: 'G',
  Electric: 'L',
  Ice: 'I',
  Fighting: 'f',
  Poison: 'o',
  Ground: 'A',
  Flying: 'v',
  Psychic: 'P',
  Bug: 'B',
  Rock: 'K',
  Ghost: 'h',
  Dragon: 'n',
  Dark: 'd',
  Steel: 'M',
  Fairy: 'y',
};